"""Pipeline to normalize the ingredients by the serving size.

Generated by trial and error directly on Atlas.
This is not the final version of the pipeline. Storing for future reference.
"""

[
    {"$project": {"name": 1, "serving_size": 1, "ingredients": 1}},
    {"$unwind": {"path": "$ingredients"}},
    {
        "$addFields": {
            "ingredients.quantity_normalized": {
                "$divide": ["$ingredients.quantity", {"$max": ["$serving_size", 1]}]
            }
        }
    },
    {
        "$group": {
            "_id": "$_id",
            "ingredients": {"$addToSet": "$ingredients"},
            "serving_size": {"$first": "$serving_size"},
        }
    },
]
